[theme]
primaryColor = "#1F77B4"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[chart]
show_rsi = true
show_macd = true
show_bollinger = true
export_enabled = true
