[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 100

[theme]
base = "dark"
primaryColor = "#4a8cff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1d24"
textColor = "#f0f2f6"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"
