[theme]
primaryColor = "#4b6cb7"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true  # Required for Streamlit Cloud
port = 8501
enableCORS = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false
