[server]
maxUploadSize = 1000  # Allows large model files
enableCORS = false    # Security setting
port = 8501           # Default port

[browser]
serverAddress = ""    # Auto-detection
gatherUsageStats = false
