# Add your actual API keys here (never share this file!)
OPENAI_API_KEY = "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"  # Get from platform.openai.com
NEWS_API_KEY = "492fa1e881394250b2eb012b0f162459"      # Get from newsapi.org
