# your_project/.streamlit/secrets.toml

# 1.NewsAPI Key (Get one from https://newsapi.org/)
NEWS_API_KEY=492fa1e881394250b2eb012b0f162459

# 2.Alpha Vantage API Key (Optional, if yfinance isn't enough. Get one from https://www.alphavantage.co/)
ALPHA_VANTAGE_API_KEY=8AUSOBVZ9ASR1SBN

# 3.Email Server Settings for OTP/Password Reset
# Example for Gmail (you might need to enable "App Passwords" for your Google account)
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_USERNAME=shreyamgm16@gmail.com
EMAIL_PASSWORD=xrimgklmhzbiucfr

EXCHANGE_RATE_API_KEY=bfb102e65ea7854f3d45c5d5

# 4.Secret key for Streamlit session management (generate a strong random string)
# e.g., import secrets; secrets.token_hex(32)
SESSION_SECRET_KEY=c6b34066623feebc1259f028c9296dde14b5f5c8c7da15df7c8fd1f43b3bb91e

# 5. Database Path
# This is a key for your database file. On Streamlit Cloud,
# the filesystem is ephemeral, so this is for demonstration or local use.
DB_PATH = "data/users.db"
