# PostgreSQL Database
[postgres]
host = "ep-hidden-resonance-adjnylsw-pooler.c-2.us-east-1.aws.neon.tech"
port = "5432"
database = "neondb"
username = "neondb_owner"
password = "npg_8ARXzaUYINB5"

# Email Service
[email]
smtp_server = "smtp.gmail.com"
smtp_port = "587"
email = "shreyamgm16@gmail.com"
password = "xrimgklmhzbiucfr"

# API Keys
[api_keys]
alpha_vantage = "8AUSOBVZ9ASR1SBN"
finnhub = "d1mp259r01qlvnp3rgn0d1mp259r01qlvnp3rgng"

[openai]
api_key = "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"

[news_api]
api_key = "492fa1e881394250b2eb012b0f162459"

# Deployment environment flag
[environment]
debug = "false"
