# streamlit/secrets_template.toml

[postgres]
host = "your-db-host"
port = "5432"
database = "your-db-name"
username = "your-username"
password = "your-password"

[email]
smtp_server = "smtp.gmail.com"
smtp_port = "587"
email = "your-email@example.com"
password = "your-app-password"  # Use app password if using Gmail

[api_keys]
alpha_vantage = "your_alpha_vantage_key"
finnhub = "your_finnhub_key"

[openai]
api_key = "your_openai_api_key"

[news_api]
api_key = "your_newsapi_key"

[environment]
debug = "false"
