# Database Configuration
[postgres]
host = "your-db-host.com"  # e.g., "localhost" or AWS RDS endpoint
port = "5432"
database = "stock_advisor"
username = "db_user"
password = "your_secure_password"  # 12+ chars with special characters

# Email Service (for password resets)
[email]
smtp_server = "smtp.gmail.com"  # For Gmail. Use "smtp.sendgrid.net" for SendGrid
smtp_port = "587"
email = "your.email@gmail.com"
password = "your-app-password"  # Gmail: use "App Password", NOT your regular password

# API Keys (Optional - for market data)
[api_keys]
alpha_vantage = "YOUR_ALPHA_VANTAGE_KEY"  # Get from https://www.alphavantage.co/
finnhub = "YOUR_FINNHUB_KEY"             # Get from https://finnhub.io

# Environment Flags
[environment]
debug = "false"  # Set to "true" for development
